driver_plugin: vagrant

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[minecraft]
  attributes:
    minecraft:
      accept_eula: true
