---
driver_plugin: vagrant

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[ubuntu]
- name: ubuntu-13.04
  run_list:
  - recipe[ubuntu]
- name: debian-6.0
  provisioner:
    sudo: false
  busser:
    sudo: false
  run_list:
  - recipe[apt]
- name: debian-7.0
  run_list:
  - recipe[apt]
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2

suites:
- name: default
  run_list:
  # - recipe[minitest-handler]
  - recipe[minecraft]
  attributes:
    minecraft:
      accept_eula: true
- name: bukkit
  run_list:
  - recipe[minitest-handler]
  - recipe[minecraft]
  - recipe[minecraft-test]
  attributes:
    minecraft:
      install_type: "bukkit"
- name: spigot
  run_list:
  - recipe[minitest-handler]
  - recipe[minecraft]
  - recipe[minecraft-test]
  attributes:
    minecraft:
      install_type: "spigot"
